/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as QaRouteImport } from './routes/qa'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ReportsNewRouteImport } from './routes/reports.new'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as QaNewRouteImport } from './routes/qa.new'
import { Route as QaIdRouteImport } from './routes/qa.$id'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as MarketplaceNewRouteImport } from './routes/marketplace.new'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as CommunitiesNewRouteImport } from './routes/communities.new'
import { Route as CommunitiesIdRouteImport } from './routes/communities.$id'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSliderRouteImport } from './routes/admin.slider'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminQaRouteImport } from './routes/admin.qa'
import { Route as AdminMarketplaceRouteImport } from './routes/admin.marketplace'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminCommunitiesRouteImport } from './routes/admin.communities'
import { Route as AdminAccommodationRouteImport } from './routes/admin.accommodation'
import { Route as AccommodationNewRouteImport } from './routes/accommodation.new'
import { Route as AccommodationIdRouteImport } from './routes/accommodation.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ReportsNewRoute = ReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QaNewRoute = QaNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => QaRoute,
} as any)
const QaIdRoute = QaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QaRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceNewRoute = MarketplaceNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketplaceRoute,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => JobsRoute,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const CommunitiesNewRoute = CommunitiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CommunitiesRoute,
} as any)
const CommunitiesIdRoute = CommunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommunitiesRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSliderRoute = AdminSliderRouteImport.update({
  id: '/slider',
  path: '/slider',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQaRoute = AdminQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketplaceRoute = AdminMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunitiesRoute = AdminCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccommodationRoute = AdminAccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => AdminRoute,
} as any)
const AccommodationNewRoute = AccommodationNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AccommodationRoute,
} as any)
const AccommodationIdRoute = AccommodationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccommodationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/qa': typeof QaRouteWithChildren
  '/search': typeof SearchRoute
  '/accommodation/$id': typeof AccommodationIdRoute
  '/accommodation/new': typeof AccommodationNewRoute
  '/admin/accommodation': typeof AdminAccommodationRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/qa': typeof AdminQaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/slider': typeof AdminSliderRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/communities/$id': typeof CommunitiesIdRoute
  '/communities/new': typeof CommunitiesNewRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/qa/$id': typeof QaIdRoute
  '/qa/new': typeof QaNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/new': typeof ReportsNewRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/qa': typeof QaRouteWithChildren
  '/search': typeof SearchRoute
  '/accommodation/$id': typeof AccommodationIdRoute
  '/accommodation/new': typeof AccommodationNewRoute
  '/admin/accommodation': typeof AdminAccommodationRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/qa': typeof AdminQaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/slider': typeof AdminSliderRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/communities/$id': typeof CommunitiesIdRoute
  '/communities/new': typeof CommunitiesNewRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/qa/$id': typeof QaIdRoute
  '/qa/new': typeof QaNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/new': typeof ReportsNewRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/qa': typeof QaRouteWithChildren
  '/search': typeof SearchRoute
  '/accommodation/$id': typeof AccommodationIdRoute
  '/accommodation/new': typeof AccommodationNewRoute
  '/admin/accommodation': typeof AdminAccommodationRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/qa': typeof AdminQaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/slider': typeof AdminSliderRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/communities/$id': typeof CommunitiesIdRoute
  '/communities/new': typeof CommunitiesNewRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/qa/$id': typeof QaIdRoute
  '/qa/new': typeof QaNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/new': typeof ReportsNewRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accommodation'
    | '/admin'
    | '/communities'
    | '/dashboard'
    | '/jobs'
    | '/marketplace'
    | '/notifications'
    | '/qa'
    | '/search'
    | '/accommodation/$id'
    | '/accommodation/new'
    | '/admin/accommodation'
    | '/admin/communities'
    | '/admin/jobs'
    | '/admin/marketplace'
    | '/admin/qa'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/slider'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/communities/$id'
    | '/communities/new'
    | '/jobs/$id'
    | '/jobs/new'
    | '/marketplace/$id'
    | '/marketplace/new'
    | '/profile/$id'
    | '/profile/edit'
    | '/qa/$id'
    | '/qa/new'
    | '/reports/$id'
    | '/reports/new'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accommodation'
    | '/communities'
    | '/dashboard'
    | '/jobs'
    | '/marketplace'
    | '/notifications'
    | '/qa'
    | '/search'
    | '/accommodation/$id'
    | '/accommodation/new'
    | '/admin/accommodation'
    | '/admin/communities'
    | '/admin/jobs'
    | '/admin/marketplace'
    | '/admin/qa'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/slider'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/communities/$id'
    | '/communities/new'
    | '/jobs/$id'
    | '/jobs/new'
    | '/marketplace/$id'
    | '/marketplace/new'
    | '/profile/$id'
    | '/profile/edit'
    | '/qa/$id'
    | '/qa/new'
    | '/reports/$id'
    | '/reports/new'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/accommodation'
    | '/admin'
    | '/communities'
    | '/dashboard'
    | '/jobs'
    | '/marketplace'
    | '/notifications'
    | '/qa'
    | '/search'
    | '/accommodation/$id'
    | '/accommodation/new'
    | '/admin/accommodation'
    | '/admin/communities'
    | '/admin/jobs'
    | '/admin/marketplace'
    | '/admin/qa'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/slider'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/communities/$id'
    | '/communities/new'
    | '/jobs/$id'
    | '/jobs/new'
    | '/marketplace/$id'
    | '/marketplace/new'
    | '/profile/$id'
    | '/profile/edit'
    | '/qa/$id'
    | '/qa/new'
    | '/reports/$id'
    | '/reports/new'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccommodationRoute: typeof AccommodationRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CommunitiesRoute: typeof CommunitiesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  JobsRoute: typeof JobsRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  QaRoute: typeof QaRouteWithChildren
  SearchRoute: typeof SearchRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ProfileIdRoute: typeof ProfileIdRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ReportsIdRoute: typeof ReportsIdRoute
  ReportsNewRoute: typeof ReportsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/reports/new': {
      id: '/reports/new'
      path: '/reports/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof ReportsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/new': {
      id: '/qa/new'
      path: '/new'
      fullPath: '/qa/new'
      preLoaderRoute: typeof QaNewRouteImport
      parentRoute: typeof QaRoute
    }
    '/qa/$id': {
      id: '/qa/$id'
      path: '/$id'
      fullPath: '/qa/$id'
      preLoaderRoute: typeof QaIdRouteImport
      parentRoute: typeof QaRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/new': {
      id: '/marketplace/new'
      path: '/new'
      fullPath: '/marketplace/new'
      preLoaderRoute: typeof MarketplaceNewRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/communities/new': {
      id: '/communities/new'
      path: '/new'
      fullPath: '/communities/new'
      preLoaderRoute: typeof CommunitiesNewRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/communities/$id': {
      id: '/communities/$id'
      path: '/$id'
      fullPath: '/communities/$id'
      preLoaderRoute: typeof CommunitiesIdRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/slider': {
      id: '/admin/slider'
      path: '/slider'
      fullPath: '/admin/slider'
      preLoaderRoute: typeof AdminSliderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/qa': {
      id: '/admin/qa'
      path: '/qa'
      fullPath: '/admin/qa'
      preLoaderRoute: typeof AdminQaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketplace': {
      id: '/admin/marketplace'
      path: '/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AdminMarketplaceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communities': {
      id: '/admin/communities'
      path: '/communities'
      fullPath: '/admin/communities'
      preLoaderRoute: typeof AdminCommunitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accommodation': {
      id: '/admin/accommodation'
      path: '/accommodation'
      fullPath: '/admin/accommodation'
      preLoaderRoute: typeof AdminAccommodationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/accommodation/new': {
      id: '/accommodation/new'
      path: '/new'
      fullPath: '/accommodation/new'
      preLoaderRoute: typeof AccommodationNewRouteImport
      parentRoute: typeof AccommodationRoute
    }
    '/accommodation/$id': {
      id: '/accommodation/$id'
      path: '/$id'
      fullPath: '/accommodation/$id'
      preLoaderRoute: typeof AccommodationIdRouteImport
      parentRoute: typeof AccommodationRoute
    }
  }
}

interface AccommodationRouteChildren {
  AccommodationIdRoute: typeof AccommodationIdRoute
  AccommodationNewRoute: typeof AccommodationNewRoute
}

const AccommodationRouteChildren: AccommodationRouteChildren = {
  AccommodationIdRoute: AccommodationIdRoute,
  AccommodationNewRoute: AccommodationNewRoute,
}

const AccommodationRouteWithChildren = AccommodationRoute._addFileChildren(
  AccommodationRouteChildren,
)

interface AdminRouteChildren {
  AdminAccommodationRoute: typeof AdminAccommodationRoute
  AdminCommunitiesRoute: typeof AdminCommunitiesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminMarketplaceRoute: typeof AdminMarketplaceRoute
  AdminQaRoute: typeof AdminQaRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSliderRoute: typeof AdminSliderRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccommodationRoute: AdminAccommodationRoute,
  AdminCommunitiesRoute: AdminCommunitiesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminMarketplaceRoute: AdminMarketplaceRoute,
  AdminQaRoute: AdminQaRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSliderRoute: AdminSliderRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CommunitiesRouteChildren {
  CommunitiesIdRoute: typeof CommunitiesIdRoute
  CommunitiesNewRoute: typeof CommunitiesNewRoute
}

const CommunitiesRouteChildren: CommunitiesRouteChildren = {
  CommunitiesIdRoute: CommunitiesIdRoute,
  CommunitiesNewRoute: CommunitiesNewRoute,
}

const CommunitiesRouteWithChildren = CommunitiesRoute._addFileChildren(
  CommunitiesRouteChildren,
)

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
  JobsNewRoute: typeof JobsNewRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
  JobsNewRoute: JobsNewRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceIdRoute: typeof MarketplaceIdRoute
  MarketplaceNewRoute: typeof MarketplaceNewRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceIdRoute: MarketplaceIdRoute,
  MarketplaceNewRoute: MarketplaceNewRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface QaRouteChildren {
  QaIdRoute: typeof QaIdRoute
  QaNewRoute: typeof QaNewRoute
}

const QaRouteChildren: QaRouteChildren = {
  QaIdRoute: QaIdRoute,
  QaNewRoute: QaNewRoute,
}

const QaRouteWithChildren = QaRoute._addFileChildren(QaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccommodationRoute: AccommodationRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CommunitiesRoute: CommunitiesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  JobsRoute: JobsRouteWithChildren,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  QaRoute: QaRouteWithChildren,
  SearchRoute: SearchRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ProfileIdRoute: ProfileIdRoute,
  ProfileEditRoute: ProfileEditRoute,
  ReportsIdRoute: ReportsIdRoute,
  ReportsNewRoute: ReportsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
